<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 12/10/2018
 * Time: 21:51
 */

namespace app\validators;


use yii\validators\Validator;

class FirstValidator extends Validator
{
    public function validateAttribute($model, $attribute)
    {
        parent::validateAttribute($model, $attribute); // TODO: Change the autogenerated stub
    }

}